# Generated by Django 5.1.7 on 2025-04-10 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_months', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('standard', 'Standardowa'), ('family', 'Rodzinna')], default='standard', max_length=10)),
                ('interest_type', models.CharField(choices=[('fixed', 'Stałe'), ('variable', 'Zmienne')], max_length=10)),
                ('first_period_interest', models.DecimalField(decimal_places=2, help_text='W skali roku, w %', max_digits=5)),
                ('margin', models.DecimalField(blank=True, decimal_places=2, help_text='Marża w %, jeśli dotyczy', max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=100)),
                ('duration_months', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('standard', 'Standardowa'), ('family', 'Rodzinna')], default='standard', max_length=10)),
                ('interest_type', models.CharField(choices=[('fixed', 'Stałe'), ('variable', 'Zmienne')], max_length=10)),
                ('first_period_interest', models.DecimalField(decimal_places=2, help_text='W skali roku, w %', max_digits=5)),
                ('margin', models.DecimalField(blank=True, decimal_places=2, help_text='Marża w %, jeśli dotyczy', max_digits=5, null=True)),
                ('bond', models.ForeignKey(blank=True, help_text='Oryginalny typ obligacji (opcjonalnie)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bonds.bond')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bonds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
