# Generated by Django 5.1.7 on 2025-04-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbond',
            name='bond',
        ),
        migrations.RemoveField(
            model_name='userbond',
            name='purchase_price',
        ),
    ]
