# Generated by Django 5.1.7 on 2025-04-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0002_remove_userbond_bond_remove_userbond_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbond',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
