# Generated by Django 5.1.7 on 2025-04-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useretf',
            name='purchase_price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
