# Generated by Django 5.1.7 on 2025-04-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0002_alter_useretf_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='useretf',
            name='euro_exchange_rate',
            field=models.DecimalField(decimal_places=4, default=4.2, max_digits=10),
            preserve_default=False,
        ),
    ]
